### ISSUE TITLE
Readme for the test

### ISSUE THREAD

**Issue by pp00704831** [sollynoay/MMP-RNN#2]
Hi,

Thank you for sharing your great code. I want to run the test code of your model, However, I do not find the Readme file for the test.
Do you plan to release the Readme file for running the testing code?

**Comment by sollynoay** [comment]
Thank you for your question. For testing the code for video deblurring, it can be realized by setting
```
para.test_only = True
```
in [main.py](https://github.com/sollynoay/MMP-RNN/blob/master/MMP-RNN/main.py) under MMP-RNN folder.  
We will later upload the pretrained weights.

**Comment by pp00704831** [comment]
Thank you for your quick reply. 
Another question is where should I put the dataset like GoPro?
Because I want to reproduce your GoPro results, what should I run for reproducing the results? 
Could you give me the full instruction or do I just need to change the line para.test_only = True? 

Thank you very much!

**Comment by sollynoay** [comment]
The gopro_lmdb folder should be under para.data_root (check [parameter.py](https://github.com/sollynoay/MMP-RNN/blob/master/MMP-RNN/para/parameter.py)). Also, para.dataset in main.py should be gopro_lmdb. The lmdb version of gopro can be downloaded [here](https://drive.google.com/file/d/1rDnbQV_YJtnAAXSG44lUWD_QzxQ9ppgL/view).

**Comment by pp00704831** [comment]
Hello,

The checkpoints seem not correct,  I can not load the checkpoints from the download file 'model_best.pth.tar'.
Could you update the pre-trained weights? Thank you very much!

**Comment by sollynoay** [comment]
Hello, the download file 'model_best.pth.tar' is the pre-trained weight for MMP estimation network, the weight for the final MMP-RNN has not been uploaded yet.

**Comment by pp00704831** [comment]
Got it! Thank you for your quick reply. I am looking forward to testing the final MMP-RNN models.

**Comment by pp00704831** [comment]
Hello, 

Thank you for your update on the GoPro results. Could you please also update the BSD results or the pre-trained weights? 
Besides, how many frames do you use during testing on the GoPro dataset?
